In [1]:
import numpy as np # import numpy package
arr_1D = np.array([2,4,6,8]) # create  NumPy 1D array which contain int value 2,4,6,8
print(arr_1D) # print arr_1D

[2 4 6 8]


In [9]:
arr_2D = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]]) # Create Numpy 2D array which contain inter type valye
print(arr_2D) # print arr_1D

[[0 1 1]
 [1 0 1]
 [1 1 0]]


In [10]:
arr_3D = np.array([[[0, 1, 1], [1, 0, 1], [1, 1, 0]]]) # create numpy 3D array which contain integer values
print(arr_3D)

[[[0 1 1]
  [1 0 1]
  [1 1 0]]]


In [11]:
# store student information in NumPy 2D array
student_info = np.array([['id', 'name', 'percentage', 'pass or fail'], 
                         [101, 'Narendra', 80, 'pass'], 
                         [102, 'John', 75, 'pass'],
                         [103, 'Abraham',33, 'fail'],
                         [104, 'Oprah',52, 'pass']
                        ])
print(student_info)

[['id' 'name' 'percentage' 'pass or fail']
 ['101' 'Narendra' '80' 'pass']
 ['102' 'John' '75' 'pass']
 ['103' 'Abraham' '33' 'fail']
 ['104' 'Oprah' '52' 'pass']]


In [12]:
percentage = np.array([80, 75, 33, 52], dtype = float) # set data type as float
print(percentage) 

[80. 75. 33. 52.]


In [13]:
arr_2D = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]]) # create NumPy 2D array
print("2D array : \n", arr_2D) # print array
 
array_size = np.size(arr_2D) # find the size of arr-2D
 
print('Size of arr_2D = ', array_size) # print size of array

2D array : 
 [[0 1 1]
 [1 0 1]
 [1 1 0]]
Size of arr_2D =  9


In [15]:
#If you want to count how many items in a row or a column of NumPy array. Then give the axis argument as 0 or 1.

In [14]:
items_in_col = np.size(arr_2D, axis = 0) # give columns 
print("No. of items in a column = ", items_in_col )
 
items_in_row = np.size(arr_2D, axis = 1)
print("No. of items in a row = ", items_in_row )

No. of items in a column =  3
No. of items in a row =  3


**1-D SHAPE OF NUMPY**

In [16]:
arr_1D = np.array([1, 2, 3]) # create 1D array
print("One dimentional NumPy array : \n", arr_1D) # print arr_1D
 
shape_of_arr_1D = np.shape(arr_1D) # find shape of NumPy Array arr_1D
print("Shape of arr_1D = ", shape_of_arr_1D) # print shape_of_arr_1D

One dimentional NumPy array : 
 [1 2 3]
Shape of arr_1D =  (3,)


In [27]:
arr_2D = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]) # create 2D array
print("Two array : \n", arr_2D) # print arr_2D
 
shape_of_arr_2D = np.shape(arr_2D) # find shape of NumPy array arr_2D
print("Shape of arr_2D = ", shape_of_arr_2D) # print shape_of_arr_2D
#OUTPUT-The np.shape() gives a return of two-dimensional array in a  pair of rows and columns tuple (rows, columns).

Two array : 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape of arr_2D =  (3, 3)


In [26]:
arr_3D = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]) # create 3D array
print("Three dimensional NumPy Array : \n", arr_3D)
 
shape_of_arr_3D = np.shape(arr_3D) # find shape of NumPy array arr_3D
print("Shape of arr_3D = ", shape_of_arr_3D) # print shape_of_arr_3D
#OUTPUT-The np.shape() gives a return of three-dimensional array in a  tuple (no. of 2D arrays, rows, columns).

Three dimensional NumPy Array : 
 [[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
Shape of arr_3D =  (3, 3, 3)


**MATHEMATICAL FUNCTION USED IN NUMPY**

In [28]:
#Creating two arrays using np.arange() function and reshape it in 2D using np.reshape() function.
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
 
# print arr1 and arr2
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Addition of Two Numpy Array**

In [30]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**Subtraction of Two NumPy Array**

In [32]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Division of Two NumPy Array**

In [35]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Multiplication of Two NumPy Array**

In [37]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [38]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**Matrix Product of Two NumPy Array (matrix)**

In [40]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [42]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

**NumPy Mathematical Built-in functions**

In [43]:
arr1.min()

1

In [44]:
arr2.max()

9

In [45]:
arr1.argmax() # return index of max value of an array

8

In [46]:
arr1.argmin() # return index of min value of an array

0

In [47]:
np.sum(arr1)

45

In [50]:
np.sum(arr1, axis = 0) # return sum of each column

array([12, 15, 18])

In [51]:
np.sum(arr1, axis = 1) # return sum of each row

array([ 6, 15, 24])

In [52]:
	
np.mean(arr1)

5.0

In [53]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

**RANDOM METHOD**

In [54]:
import random # import random module

In [55]:
#This function generates float value between 0.0 to 1.0 and returns ndarray if you will give shape.
rd_num = np.random.random(1)
rd_2D_array =  np.random.random((3,3))
print(rd_num)
print(rd_2D_array)

[0.45489504]
[[0.76813614 0.96263015 0.29768733]
 [0.28811586 0.56212042 0.11783264]
 [0.55378073 0.03567141 0.3210079 ]]


In [56]:
#np.random.randint()
#The random integer function generates single random integer number from given range and if the shape will give then return ndarray.
rd_no = np.random.randint(1,4)
rd_2D_arr = np.random.randint(1,4, (4,4))
rd_3D_arr = np.random.randint(1,4, (2,4,4))
 
print(rd_no)
print(rd_2D_arr)
print(rd_3D_arr)

1
[[3 1 3 1]
 [1 1 3 3]
 [2 3 1 3]
 [3 1 3 2]]
[[[2 3 3 2]
  [3 2 3 2]
  [1 2 2 2]
  [1 2 3 2]]

 [[3 3 2 2]
  [2 3 3 3]
  [3 3 2 2]
  [3 1 2 3]]]


In [57]:
#np.random.seed()
#The random module generates random number but next time you want to generate the same number then seed() will help.
np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


In [58]:
#np.random.rand()
#The rand() function work like random() but it accept shape and return ndarray which contain random values between 0.0 to 1.0.
arr_2D = np.random.rand(3,3) # return  3 x 3 matrix
print(arr_2D)

[[0.13145815 0.41366737 0.77872881]
 [0.58390137 0.18263144 0.82608225]
 [0.10540183 0.28357668 0.06556327]]


In [59]:
#np.random.choice()
#If you have sequence values and want to get random single value then the random choice() function is the best choice.
x = [1,2,3,4] # list
choice_from_x = np.random.choice(x) # retun random single item from sequence
print(choice_from_x )

2


In [61]:
for i in range(20):
    print(np.random.choice(x)) #It change after one iteration

4
1
2
1
3
1
1
1
2
1
4
1
1
3
1
3
3
1
4
2
